### ISSUE TITLE
Cannot able to install faster-than-csv

### ISSUE THREAD

**Issue by pawarashish564** [juancarlospaco/faster-than-csv#11]
**Describe the bug**
I'm installing it in my local machine using pip, pipenv and getting the following errors.

**Expected behavior**
I should be installed as the other packages I install.
**Screenshots**
![image](https://user-images.githubusercontent.com/29516182/114662866-09411180-9d17-11eb-8a43-c45a2619d9d7.png)
![image](https://user-images.githubusercontent.com/29516182/114663507-11e61780-9d18-11eb-8ab8-390498fa0bc9.png)

**Desktop**
 - OS: Microsoft Windows 10 Home Single Language
 - Browser  chrome
 - Version 10.0.19042 N/A Build 19042

**Comment by juancarlospaco** [comment]
- You need CPython 3.9 or higher.
- You need to use system shell terminal window, cmd.exe or Powershell.
- Only the official Python is supported, not Anaconda because we dont use it and dont know it.
- [You need to download and install these DLL, and reboot.](https://nim-lang.org/download/dlls.zip)

**Comment by pawarashish564** [comment]
Okay thanks for help
