### ISSUE TITLE
No line identification?

### ISSUE THREAD

**Issue by viniciusban** [juancarlospaco/faster-than-csv#2]
```
>>> import faster_than_csv as csv
>>> csv.csv2list("sample.csv")
['1', '2', '3', '4', '10', '20', '30', '40', '100', '200', '300', '400']
```

Is it a planned feature, all columns in a single list, despite of rows?

**Comment by juancarlospaco** [comment]
Yes. Its designed to return just a list, for when you only need a list.
For more structured results, see:

- `csv2dict()` :arrow_right: `dict()`.
- `csv2json()` :arrow_right: JSON.
- `csv2json_pretty()` :arrow_right: JSON Pretty-Printed.
- `csv2ndjson()` :arrow_right: JSON of NDJSON https://github.com/ndjson/ndjson-spec
- `csv2htmltable()` :arrow_right: HTML Table.

:smile:
