### ISSUE TITLE
Error at building docker image for benchmarking.

### ISSUE THREAD

**Issue by verdug0** [juancarlospaco/faster-than-csv#6]
**Describe the bug**
/tmp/faster_than_csv.nim(17, 92) template/generic instantiation of `exportpy` from here
/tmp/faster_than_csv.nim(16, 1) template/generic instantiation of `exportpyAuxAux` from here
/tmp/faster_than_csv.nim(19, 15) Error: undeclared identifier: 'CsvParser'
The command '/bin/sh -c nim c -d:release --app:lib --passL:"-s" --gc:markAndSweep --passC:"-march=native" --passC:"-flto" --passC:"-ffast-math" --out:/tmp/faster_than_csv.so /tmp/faster_than_csv.nim' returned a non-zero code: 1

**To Reproduce**
Just build the docker.

Fix: 
I don't have a fix for this yet.

**Comment by verdug0** [comment]
Really fast response. Thanks again JCP. ;)

**Comment by verdug0** [comment]
Open to show you another bug in build-docker image:

This was building in Linux Mint 19.2, i think is possible to be in ubuntu too.

Setting up g++-9 (9.2.1-21ubuntu1) ...
Setting up python3-keyring (18.0.1-1) ...
Processing triggers for libc-bin (2.30-0ubuntu2) ...
Processing triggers for mime-support (3.64ubuntu1) ...
Removing intermediate container 439babcb7ca7
 ---> de4627ea453b
Step 4/11 : RUN pip3 install --upgrade pip==19.3.1 ; pip3 install --upgrade pandas==0.24.2
 ---> Running in bb0cabcca2e7
Collecting pip==19.3.1
  Downloading https://files.pythonhosted.org/packages/00/b6/9cfa56b4081ad13874b0c6f96af8ce16cfbc1cb06bedf8e9164ce5551ec1/pip-19.3.1-py2.py3-none-any.whl (1.4MB)
Installing collected packages: pip
  Found existing installation: pip 18.1
    Not uninstalling pip at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'pip'. No files were found to uninstall.
Successfully installed pip-19.3.1
Traceback (most recent call last):
  File "/usr/bin/pip3", line 11, in <module>
    sys.exit(main())
TypeError: 'module' object is not callable
The command '/bin/sh -c pip3 install --upgrade pip==19.3.1 ; pip3 install --upgrade pandas==0.24.2' returned a non-zero code: 1

---

Seems to be because python3-pip is broken.
https://github.com/pypa/pip/issues/5599
---

Locally fixed:

diff --git a/Dockerfile b/Dockerfile
index 9d5c8e3..043fb1a 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -1,7 +1,7 @@
 FROM nimlang/nim
 RUN rm -rf /tmp/*
 RUN apt-get update -y --quiet ; apt-get install -y python3-pip python3-numpy
-RUN pip3 install --upgrade pip==19.3.1 ; pip3 install --upgrade pandas==0.24.2
+RUN python3 -m pip install --upgrade pip==19.3.1 ; pip3 install --upgrade pandas==0.24.2

**Comment by juancarlospaco** [comment]
PIPEnv and PIP get broken very often lately.
I even made my own PIP that works with PIP/PIPEnv broken as a backup: https://github.com/juancarlospaco/plz#plz
:crying_cat_face:

**Comment by verdug0** [comment]
Awesome, also, OT: great post, clap clap
https://dev.to/juancarlospaco/design-by-contract-immutability-side-effects-and-gulag-44fk
Has pensado en armar una meetup de Nim en Buenos Aires?

**Comment by juancarlospaco** [comment]
https://www.meetup.com/Nim-Argentina
